# Generated by Django 4.2.5 on 2024-01-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Datetime when this object was created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Datetime when this object was last modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of animal like lion,tiger,etc..", max_length=64
                    ),
                ),
                ("age", models.FloatField(help_text="Age of animal in years")),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Herbivore"), (2, "Carnivore"), (3, "Omnivore")],
                        default=0,
                        help_text="Type of animal based on food",
                    ),
                ),
                ("sound", models.CharField(help_text="Sound of animal", max_length=64)),
                ("color", models.CharField(help_text="Color of animal", max_length=64)),
            ],
        ),
        migrations.AddConstraint(
            model_name="animal",
            constraint=models.CheckConstraint(
                check=models.Q(("age__gte", 0)), name="age_should_be_greater_than_zero"
            ),
        ),
    ]
