# Generated by Django 4.2.5 on 2024-01-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="deleted_on",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="When this animal was deleted from our database",
                null=True,
            ),
        ),
    ]
