# Generated by Django 4.2.5 on 2024-01-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_animal_deleted_on"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="animal",
            name="age_should_be_greater_than_zero",
        ),
        migrations.AlterField(
            model_name="animal",
            name="type",
            field=models.IntegerField(
                choices=[(1, "Herbivore"), (2, "Carnivore"), (3, "Omnivore")],
                default=1,
                help_text="Type of animal based on food",
            ),
        ),
        migrations.AddConstraint(
            model_name="animal",
            constraint=models.CheckConstraint(
                check=models.Q(("age__gt", 0)), name="age_should_be_greater_than_zero"
            ),
        ),
    ]
